-- ----------------------------
-- Records of role and user
-- ----------------------------
-- INSERT INTO `ttmt_user_role` (user_id, role_id)
-- VALUES (3, 1);
-- INSERT INTO `ttmt_user_role` (user_id, role_id)
-- VALUES (3, 2);
-- INSERT INTO `ttmt_user_role` (user_id, role_id)
-- VALUES (4, 2);
